stages:
  - package

workflow:
  rules:
    # On commit on branch
    - if: $CI_COMMIT_BRANCH
      variables:
        CI_DATA: "branch=${CI_COMMIT_BRANCH}"
    # On tag
    - if: $CI_COMMIT_TAG
      variables:
        CI_DATA: "tag=${CI_COMMIT_TAG}"

package:
  stage: package
  script:
    - apt update
    - apt install curl -y
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data ${CI_DATA} "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
